# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: JDI-Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Download Chrome driver
      run: |
        python get_driver.py
    - name: Run tests
      run: |
        python -m unittest Test\jdi_uitests_webtests\test\run_all_tests.py -v
      shell: cmd
    - name: Save debug log file
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: debug.log
      if: ${{ always() }}
    - name: Save jdi log file
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: jdi.log
      if: ${{ always() }}
